### PR TITLE
Publish Python wheel

### LINKED ISSUE #133: Publish Python wheel files
Currently only a tar.gz is published [on pypi](https://pypi.python.org/pypi/ccxt) but since the code is both py2 and 3 compatible a .whl file should be uploaded as well, which is only a fraction of the size of the tarball.

### PR DESCRIPTION
**Pull request by thijstriemstra**
fixes #133

### CODE REVIEW

**Comment by kroitor** [comment]
thx!

**Comment by kroitor** [comment]
Nope, it didn't work:

https://travis-ci.org/kroitor/ccxt/builds/266761715 (see the very end of build log, under deployment)

screen shot 2017-08-21 at 14 18 30

**Comment by thijstriemstra** [comment]
See https://docs.travis-ci.com/user/deployment/pypi/#Uploading-different-distributions. What did I miss?

**Comment by thijstriemstra** [comment]
`pip3 install wheel` probably needs to be added to travis.yml.

**Comment by kroitor** [comment]
> What did I miss?

I don't know yet, but I told you it's not as easy as it may seem at first ))
I'll try pip3 install wheel now...

**Comment by kroitor** [comment]
No, pip3 install wheel didn't help. Any ideas? It seems like it cannot find dist/* (whatever it means)...

**Comment by kroitor** [comment]
Changed `pip3 install wheel` to `pip install wheel` and it worked! ) thx!

**Comment by kroitor** [comment]
@thijstriemstra I have a question, can you tell me how these wheels are actually built? I don't really know their system, what's a universal wheel and what other types of wheels are there... I can see it's a universal wheel (which is meant to be py2-py3 compatible). But the code now has an `async` subpackage that only works with 3.5+. And the deps for it are determined in setup.py (conditional install depending on which version of python is used). So, if the wheel is universal, does it include the async subpackage or not?

**Comment by thijstriemstra** [comment]
it includes the subpackage. Should be fine. Tested on Python 3.5 and 2.7 just now.

**Comment by kroitor** [comment]
@thijstriemstra awesome, thanks!

**Pull request merged**
