### PR TITLE
Move wiki documentation into repository

### LINKED ISSUE #134: Move wiki docs inside the ccxt repo
Move the wiki documentation into a Sphinx rst format/project in a `doc/` directory. It can then be published on https://readthedocs.org/.

### PR DESCRIPTION
**Pull request by thijstriemstra**
fixes #134

### CODE REVIEW

**Comment by kroitor** [comment]
I'll be waiting for your signal, when you're ready.

**Comment by kroitor** [comment]
@thijstriemstra yep, they have some lags occasionally, no big deal, should appear in travis soon.

**Comment by thijstriemstra** [comment]
@kroitor, you want to keep using markdown syntax right?

**Comment by kroitor** [comment]
An update from Travis:

screen shot 2017-08-21 at 16 40 41

https://www.traviscistatus.com/incidents/tjfn9tf5vp83

**Comment by thijstriemstra** [comment]
It's possible to use RestructuredText (the default) or Markdown. I'll stick to Markdown syntax.

**Comment by kroitor** [comment]
Oh, I'm sorry, I forgot the following:

There's a script called export-exchanges.js that exports the list of exchanges with their urls and logos from ccxt to the docs and to the readme file. So, if we change the folder for the docs, I will redirect it.

**Comment by kroitor** [comment]
Oh, I'm sorry, I forgot the following:

There's a script called export-exchanges.js that exports the list of exchanges with their urls and logos from ccxt to the docs (currently, into the ccxt.wiki subfolder cloned upon build) and to the readme file. So, if we change the folder for the docs, I will redirect it.

**Comment by thijstriemstra** [comment]
The project that brings markdown support to Sphinx is running behind and seems quite buggy: https://github.com/rtfd/recommonmark I couldn't get it to work with the latest version of Sphinx and older versions are also not working very well. Perhaps we should switch to restructuredtext which works properly..

**Comment by kroitor** [comment]
Travis has finally noticed this PR (it was a GitHub issue actually), but there's an install/doc error:

https://travis-ci.org/kroitor/ccxt/builds/266800020

```
$ tox -e qa,doc
qa create: /home/travis/build/kroitor/ccxt/.tox/qa
qa installdeps: .[qa]
qa installed: aiodns==1.1.1,aiohttp==2.2.5,async-timeout==1.2.1,cchardet==2.1.1,ccxt==1.4.62,chardet==3.0.4,flake8==3.4.1,mccabe==0.6.1,multidict==3.1.3,pycares==2.3.0,pycodestyle==2.3.1,pyflakes==1.5.0,yarl==0.12.0
qa runtests: PYTHONHASHSEED='1397682737'
qa runtests: commands[0] | flake8
./doc/conf.py:78:4: E121 continuation line under-indented for hanging indent
ERROR: InvocationError: '/home/travis/build/kroitor/ccxt/.tox/qa/bin/flake8'
doc create: /home/travis/build/kroitor/ccxt/.tox/doc
doc installdeps: .[doc]
doc installed: aiodns==1.1.1,aiohttp==2.2.5,alabaster==0.7.10,async-timeout==1.2.1,Babel==2.5.0,cchardet==2.1.1,ccxt==1.4.62,certifi==2017.7.27.1,chardet==3.0.4,CommonMark==0.5.4,docutils==0.14,idna==2.6,imagesize==0.7.1,Jinja2==2.9.6,MarkupSafe==1.0,multidict==3.1.3,pycares==2.3.0,Pygments==2.2.0,pytz==2017.2,recommonmark==0.4.0,requests==2.18.4,six==1.10.0,snowballstemmer==1.2.1,Sphinx==1.6.3,sphinxcontrib-websupport==1.0.1,urllib3==1.22,yarl==0.12.0
doc runtests: PYTHONHASHSEED='1397682737'
doc runtests: commands[0] | sphinx-build -W -b html -d /home/travis/build/kroitor/ccxt/.tox/doc/tmp/doctrees . /home/travis/build/kroitor/ccxt/.tox/doc/tmp/html
Running Sphinx v1.6.3
making output directory...
loading pickled environment... not yet created
loading intersphinx inventory from https://docs.python.org/objects.inv...
intersphinx inventory has moved: https://docs.python.org/objects.inv -> https://docs.python.org/2/objects.inv
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 1 source files that are out of date
updating environment: 1 added, 0 changed, 0 removed
reading sources... [100%] index
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [100%] index
generating indices... genindex
writing additional pages... search
copying static files... 
Warning, treated as error:
html_static_path entry '/home/travis/build/kroitor/ccxt/doc/_static' does not exist
ERROR: InvocationError: '/home/travis/build/kroitor/ccxt/.tox/doc/bin/sphinx-build -W -b html -d /home/travis/build/kroitor/ccxt/.tox/doc/tmp/doctrees . /home/travis/build/kroitor/ccxt/.tox/doc/tmp/html'
___________________________________ summary ____________________________________
ERROR:   qa: commands failed
ERROR:   doc: commands failed
```

screen shot 2017-08-21 at 17 34 43

**Comment by kroitor** [comment]
It seems like it cannot find the `./doc/_static` folder this time...

**Comment by kroitor** [comment]
@thijstriemstra hi) how are we on this? what's the plan? )

**Comment by thijstriemstra** [comment]
Weird, that error is a warning on my local machine:

```
generating indices... genindex
writing additional pages... search
copying static files... WARNING: html_static_path entry '/Users/thijstriemstra/projects/ccxt/doc/_static' does not exist
done
copying extra files... done
dumping search index in English (code: en) ... done
dumping object inventory... done
build succeeded, 1 warning.

Build finished. The HTML pages are in _build/html.
```

I'll try to work around it.

> @thijstriemstra hi) how are we on this? what's the plan? )

It might take a day or two to get this finished, hold tight.

**Comment by thijstriemstra** [comment]
@kroitor can you signup (https://readthedocs.org/accounts/signup/) and register ccxt on rtfd in the meantime?

**Comment by kroitor** [comment]
@thijstriemstra sure, did it already! I'm not very familiar with it, have to import this GitHub project I suppose, I will read more about it and get back to you asap.

**Comment by kroitor** [comment]
@thijstriemstra now I see this (as I haven't used it before, your guidance will be appreciated):

screen shot 2017-08-23 at 02 31 24

**Comment by kroitor** [comment]
https://readthedocs.org/projects/ccxt/builds/5871064/

screen shot 2017-08-23 at 02 33 32

```shell
python /home/docs/checkouts/readthedocs.org/user_builds/ccxt/envs/latest/bin/sphinx-build -T -b readthedocs -d _build/doctrees-readthedocs -D language=en . _build/html
Running Sphinx v1.5.3
making output directory...
loading translations [en]... done
loading pickled environment... not yet created
building [mo]: targets for 0 po files that are out of date
building [readthedocs]: targets for 7 source files that are out of date
updating environment: 7 added, 0 changed, 0 removed
reading sources... [ 14%] CHANGELOG
reading sources... [ 28%] CONTRIBUTING
reading sources... [ 42%] README
reading sources... [ 57%] examples/README
reading sources... [ 71%] examples/js/README
reading sources... [ 85%] examples/php/README
reading sources... [100%] examples/py/README


Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/ccxt/envs/latest/lib/python2.7/site-packages/sphinx/cmdline.py", line 296, in main
    app.build(opts.force_all, filenames)
  File "/home/docs/checkouts/readthedocs.org/user_builds/ccxt/envs/latest/lib/python2.7/site-packages/sphinx/application.py", line 333, in build
    self.builder.build_update()
  File "/home/docs/checkouts/readthedocs.org/user_builds/ccxt/envs/latest/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 251, in build_update
    'out of date' % len(to_build))
  File "/home/docs/checkouts/readthedocs.org/user_builds/ccxt/envs/latest/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 265, in build
    self.doctreedir, self.app))
  File "/home/docs/checkouts/readthedocs.org/user_builds/ccxt/envs/latest/lib/python2.7/site-packages/sphinx/environment/__init__.py", line 560, in update
    self.doc2path(config.master_doc))
SphinxError: master file /home/docs/checkouts/readthedocs.org/user_builds/ccxt/checkouts/latest/index.rst not found

Sphinx error:
master file /home/docs/checkouts/readthedocs.org/user_builds/ccxt/checkouts/latest/index.rst not found

```

**Comment by kroitor** [comment]
@thijstriemstra  I've added you to the project maintainers on readthedocs.org )

**Comment by kroitor** [comment]
@thijstriemstra hey, it's me again ) What's our next move on this? ;)

**Comment by thijstriemstra** [comment]
@kroitor I don't know, I said I needed a few days. But you can merge this PR as is, and help port the wiki to sphinx/rst.

**Comment by kroitor** [comment]
> @thijstriemstra  I don't know, I said I needed a few days. 

Oh, I'm sorry I must have missed that, excuse me for annoying )

> But you can merge this PR as is, and help port the wiki to sphinx/rst.

I really wish to help, but I need your guidance, as I am not familiar with sphinx. If you tell me what needs to be done for it – I'll do that.

Thx for your help, sorry again for bothering.

**Comment by kroitor** [comment]
@thijstriemstra what should be done for porting? I mean, we already have pandoc there, and it does .md → .rst conversion in one command, or you mean something beyond that?

**Comment by thijstriemstra** [comment]
@kroitor you're not annoying, don't worry ;) Yes pandoc needs to be run once and the resulting documents all need a header and be checked if they look ok. I will add an example so you see what I mean.

**Comment by kroitor** [comment]
@thijstriemstra ok, I will convert them and will put them into the ./doc folder. An example would be helpful as well )

**Comment by thijstriemstra** [comment]
@kroitor I added the installation document as an example. Steps I took:

- add `install.rst` to `index.rst`
- convert `Install.md` to `install.rst` (think we should use lowercase names) using this command:
```
pandoc --from=markdown --to=rst --output=install.rst /path/to/ccxt.wiki/Install.md
```

**Comment by thijstriemstra** [comment]
I've added one more, `checklist`.

**Comment by thijstriemstra** [comment]
> now I see this (as I haven't used it before, your guidance will be appreciated):

This should be fixed as soon you merge this PR. Double-checking the rtd config now.

**Comment by thijstriemstra** [comment]
> Because, if we convert from ccxt.wiki, we will loose all benefits of moving inside the repo in the first place

I don't get it, what do you mean?

**Comment by thijstriemstra** [comment]
And if you want to stick to markdown, I guess Sphinx is not an option (and you won't be able to publish on readthedocs.io).

**Comment by kroitor** [comment]
@thijstriemstra I'm going to do it this way: I will use markdown and will convert to rst upon build and upload to readthedocs upon build, so, it should not be a problem to setup. Will read more on configuring it and hope to finish this asap.

**Comment by thijstriemstra** [comment]
Ok, if you prefer markdown that's a way to do it. Sounds like overkill to me but hey.

**Comment by kroitor** [comment]
@thijstriemstra I don't get it, what do you mean?

I mean, I want to stick to md, and want to move md from ccxt.wiki folder into the repo as well ) And convert to rst from there )

**Comment by thijstriemstra** [comment]
Converting the market list table to rst didn't go well with pandoc so that could be a showstopper.

**Comment by kroitor** [comment]
@thijstriemstra Yeah, I've been struggling with that table and with PyPI's *very specific* rst flavor for weeks ) Even had to develop the strategy and tactics of dealing with it ) Hope to win some day )))

**Comment by kroitor** [comment]
@thijstriemstra to convert that table we had to fallback to regexps. First we convert it with pandoc, and then we replace the table with a js script. That is also done upon build. I will port it into the repo as well.

**Comment by kroitor** [comment]
I hope to finish this tomorrow, after we change all settings and test it thoroughly. Thanks a lot for your huge effort! Really appreciate it, man!

**Comment by kroitor** [comment]
@thijstriemstra after looking deeper into it I came to  conclusion, that you are right – supporting md to rst conversion just for the sake of keeping the markdown flavor is an overkill. We are switching to rst entirely.

**Comment by kroitor** [comment]
For converting `md` to `rst` without ruining the tables, we use the following command:

```shell
pandoc --wrap=preserve --columns=10000 --from=markdown --to=rst --output=doc/install.rst ccxt.wiki/Install.md
```

As you see, this preserves original wrapping and sets column width to 10000, which is more than enough for most tables we have there. Also, this option is only supported in latest pandoc versions 1.19.x. But don't worry about it, I will do everything that's left.

**Comment by thijstriemstra** [comment]
Makes sense.

**Comment by kroitor** [comment]
@thijstriemstra I'm sorry, I got one more question: how do you set up an index page for the docset? Is there such a parameter or an option? Maybe a default name for the index file?

**Comment by kroitor** [comment]
Ok, this is now converted to rst and merged, I will have to work on this to edit links, etc.. But contributors can help me with do that now, so thank you again for this!

**Comment by kroitor** [comment]
@thijstriemstra can you take a look at this: https://travis-ci.org/kroitor/ccxt/builds/268402670
Sphinx/Travis is complaining about some _1broker identifier, I don't really understand what it's saying.

**Comment by kroitor** [comment]
@thijstriemstra seems like it doesn't like image references in the table, is there a way to put an image into a table in rst at all? We had to strip the first column with images off that table before publishing to PyPI, that is done in update-badges.js:

```JavaScript
let rst = fs.readFileSync (readmeRst, 'utf8')
let rstNew = 
    rst.replace (/\`([^\`]+)\s\<\#[^\`]+\>\`\_\_/g, '$1') // PyPI doesn't like urls containing anchor hash symbol '#', strip it off to plain text
        .replace (/\\\|/g, '|') // PyPI doesn't like escaped vertical bars

let rstExchangeTableRegex = /([\s\S]+?)APIs:[\n][\n](\+\-\-[\s\S]+\-\-\+)[\n][\n]([\s\S]+)/
let match = rstExchangeTableRegex.exec (rstNew)
let rstExchangeTableLines = match[2].split ("\n")

let newRstExchangeTable = rstExchangeTableLines.map (line => {
    return line.replace (/(\||\+)(.).+?(\s|\=|\-)(\||\+)/, '$1') // replace ascii table graphics
}).join ("\n")
```

**Comment by kroitor** [comment]
http://ccxt.readthedocs.io/en/latest/index.html

**Comment by kroitor** [comment]
I'm starting to hate RTD already %))))

rtd

**Comment by kroitor** [comment]
hyphenation

**Pull request merged**
