### PR TITLE
Add more market urls

### PR DESCRIPTION
**Pull request by thijstriemstra**
refs #108

### CODE REVIEW

**Comment by thijstriemstra** [comment]
@kroitor added the market urls, can you take a look or merge, there are some urls that have a different structure it seems.

**Comment by kroitor** [comment]
@thijstriemstra thx! I'll be able to do that in several hours and I will let you know, of course!

**Comment by kroitor** [comment]
Hmm... Don't know why would you hardcore all of them instead of templating, like it was in both examples... Or did I miss something?

**Comment by kroitor** [comment]
The point was to implement getMarketURL/get_market_url for all of them %)

**Comment by thijstriemstra** [comment]
> Hmm... Don't know why would you hardcore all of them instead of templating, like it was in both examples... Or did I miss something?

No that still needs to be done.

**Comment by kroitor** [comment]
Oops, sorry for my misunderstanding )

**Comment by kroitor** [comment]
No worries, I will still merge this PR and will write the methods needed. Thx!

**Pull request merged**
