### PR TITLE
Uniformizing createOrder return for bittrex and poloniex

### PR DESCRIPTION
**Pull request by Nilotaviano**

### CODE REVIEW

**Comment by kroitor** [comment]
Thanks! You forgot to put an 'await' keyword there before the `this[method] ()` call ) And we will probably not call that uuid, because that stands for Unique User ID (why would bittrex and poloniex copypaste it ;)) We will call that an 'id'. But, your code is still good, almost how we wanted it, so I will fix and merge it very soon )

**Comment by Nilotaviano** [comment]
I called it UUID mainly because it's how bittrex calls it, but it stands for "universally unique identifier" IIRC.

**Comment by Nilotaviano** [comment]
Thank you!

**Comment by kroitor** [comment]
Oh, I see... anyway, that's just the id of the order, as it is ) So, as you can see, I merged your code into master ) It's already available in newly built version 1.3.19 ) Thanks!

**Comment by Nilotaviano** [comment]
Yup, naming it 'id' is just as fine. Thanks!

**Pull request merged**
