### PR TITLE
Use PEP 8 for Python code

### LINKED ISSUE #104: Use PEP 8 for Python code
I hardly ever see the style 'functionName ()' being used in Python and it would be cool if this library could follow the PEP8 standard for python code. So it becomes 'functionName()'. There is a library called `flake8` that can lint the code and run during a Travis build to catch mistakes.

If you like this idea, I can work on a pull request.

### PR DESCRIPTION
**Pull request by thijstriemstra**
fixes #104

### CODE REVIEW

**Comment by kroitor** [comment]
Standing by for your command )

**Comment by kroitor** [comment]
@thijstriemstra , I'm sorry, can you please save the whitespace before the opening brackets `(` and `{` ? We are making them intentionally for readability, because we think that whitespaces actually improves readability.

We know that it may contradict this PEP 8 recommendation:

```
Whitespace in Expressions and Statements
Avoid extraneous whitespace in the following situations:
Immediately before the open parenthesis that starts the argument list of a function call:

Yes: spam(1)
No:  spam (1)
```

But, at the same time they say:

```
Some other good reasons to ignore a particular guideline:
- When applying the guideline would make the code less readable, even for someone who is used to reading code that follows this PEP.
```

Therefore it's not a violation in general sense. Is that possible to preserve that whitespace? Thx!

**Comment by thijstriemstra** [comment]
Ehm, the reason I opened #104 was because the whitespace before the opening brackets ( and { is not a common Python style and makes it harder to read.

**Comment by kroitor** [comment]
I thought the reason for opening #104 was the uppercase functionName notation, not the whitespace. That whitespace is sometimes also necessary for correct transpilation.

But, you know, if you can continue with this and let me know when you're done, I will merge everything that's possible to merge, including the edited whitespace. I will alter the transpiler if that is necessary to satisfy all PEP 8 recommendations. I think, we'll be ok with this.

**Comment by thijstriemstra** [comment]
@kroitor ah I see, you thought I meant a camel-case kind of thing. Thanks for feedback.

**Comment by kroitor** [comment]
@thijstriemstra yes, but, if that's how Python coders want it - no problem, I will still merge it, and I'll do it Python-style with your help )

**Comment by thijstriemstra** [comment]
flake8 also uncovered 2 bugs it seems:

```
$ flake8 __init__.py 
__init__.py:6384:53: F821 undefined name 'buy'
__init__.py:7175:12: F821 undefined name 'api'
```

**Comment by kroitor** [comment]
> flake8 also uncovered 2 bugs it seems:

Thanks, I'll check and fix that as well!

**Comment by thijstriemstra** [comment]
I've fixed them in the branch as well:

```diff
diff --git a/ccxt/__init__.py b/ccxt/__init__.py
index a3f65ef..ee96330 100644
--- a/ccxt/__init__.py
+++ b/ccxt/__init__.py
@@ -6381,7 +6381,7 @@ class coincheck (Exchange):
         if type == 'market':
             order_type = type + '_' + side
             order['order_type'] = order_type
-            prefix = (order_type + '_') if (side == buy) else ''
+            prefix = (order_type + '_') if (side == 'buy') else ''
             order[prefix + 'amount'] = amount
         else:
             order['order_type'] = side
@@ -7172,7 +7172,7 @@ class coinsecure (Exchange):
     def create_order(self, market, type, side, amount, price=None, params={}):
         method = 'privatePutUserExchange'
         order = {}
-        if api == 'market':
+        if type == 'market':
             method += 'Instant' + self.capitalize(side)
             if side == 'buy':
                 order['maxFiat'] = amount
```

**Comment by thijstriemstra** [comment]
I also noticed you use `type` as a var name and technically it works but since `type` is a Python builtin I would use a different name for that var. But this can be handled in a different PR.

**Comment by kroitor** [comment]
> I've fixed them in the branch as well:

Yep, but that also requires a fix in JS and PHP, so I did it in general, no problem, will merge it. Thanks!

**Comment by kroitor** [comment]
> I also noticed you use type as a var name and technically it works but since type is a Python builtin I would use a different name for that var. But this can be handled in a different PR.

Will rename this everywhere in the file as well. Thx for the notice!

**Comment by thijstriemstra** [comment]
The pep8 fixes are ready and I'll now integrate it with travis.

**Comment by kroitor** [comment]
Don't worry about the conflicts, I will resolve them upon merging. Already doing that.

**Comment by kroitor** [comment]
@thijstriemstra can you suggest a better single-word name for the `type` argument? `order_type` seems to be very long, and it also requires an underscore, so it will be different in JS (orderType) and that's a little harder to transpile and brings naming inconsistency into code. A single word will be much better, I think... I'm trying but cannot come up with a good one.

The exchanges themselves call it `type of order` and it's everywhere:

> A market order is the simplest of the order types.

Moreover, some exchanges return `orderType = 'sell' / 'buy'` (confusing the type with bid/ask side or direction).

P.S. Why would they reserve the so-common `type` keyword in Python? %)

**Comment by thijstriemstra** [comment]
What about orderType?

> P.S. Why would they reserve the so-common type keyword in Python? %)

because it's so common and easy to remember when trying to identify a type, not sure.

**Comment by kroitor** [comment]
> What about orderType?

Wouldn't it violate the PEP?

> or otype?

ono )

I will think about it more, while merging... Probably will end up with order_type.

**Comment by thijstriemstra** [comment]
> Wouldn't it violate the PEP?

no and otherwise we'll ignore that PEP rule.

**Comment by kroitor** [comment]
I noticed you added a flask8 dependency in your most recent commits, and you use pip3 install, but we test against python 2 (we also support python3 and we can test against python3), I just wanted to make sure if everything is compatible, and that proper version numbers are used for installing dependencies. Will it work with pip (py2)?

**Comment by thijstriemstra** [comment]
@kroitor should work with pip py2 as well. This PR is ready but I'm not sure how to fix the conflicts in ccxt, there are 443 of them. Can you pick part of this PR and merge that?

**Comment by kroitor** [comment]
> This PR is ready but I'm not sure how to fix the conflicts in ccxt, there are 443 of them. Can you pick part of this PR and merge that?

Don't worry about conflicts, I will merge everything, no problem. I already did, the only file that's left is __init__.py, where I can resolve most of conflicts by tweaking the transpiler (already did that) for not including the whitespace in python-version, as for other conflicts left, I will merge them as well, no big deal. Thx for your participation in this, really appreciate it!

**Comment by thijstriemstra** [comment]
Would be nice to actually merge part of the PR instead of copy/pasting my changes so I'll be recognized as a contributor ;)

**Comment by kroitor** [comment]
> Would be nice to actually merge part of the PR instead of copy/pasting my changes so I'll be recognized as a contributor ;)

I'm not sure how to merge files from a remote pr one by one, and I have to because there may be breaking changes in the transpilation process. If you can tell me how I can tag you as a contributor, but still be able to checkout out and merge files one-by-one, I will do that, of course. I'm not sure which git command does a partial merge.

**Comment by thijstriemstra** [comment]
You can tag me as a contributor, that's fine. But you should never copy contributions by other people because it's now not clear I've contributed and I can't claim it.

**Comment by kroitor** [comment]
> You can tag me as a contributor, that's fine. 

How can I do it by merging this PR partially ? I don't know the correct git command for a *partial* case (sorry for that).

> But you should never copy contributions by other people because it's now not clear I've contributed and I can't claim it.

Don't worry, I will still do a merge of this PR (almost there), and it will recognize you as a contributor anyway.

**Comment by thijstriemstra** [comment]
If you add me as a contributor that can merge I can take a look at it. You can disable merge ability for my account afterwards if you want.


ps. to fix the pep8 violations in `__init__.py` I installed `autopep8` using pip and then run this command on the file:

```
autopep8 --in-place --select=E1,E201,E202,E211,W291,E225,E251,W293,W1 ccxt/__init__.py
```

**Comment by kroitor** [comment]
> to fix the pep8 violations in __init__.py I installed autopep8 using pip and then run this command on the file

Yep, but it actually "fixed" the generated code, and it will be rewritten discarding all "fixes" upon next build/regeneration, so, to fix it properly I am editing the transpilation/generator rules in transpile.js.

P.S. Don't worry about being accounted as a contributor, I will do it properly, and you will be able to claim this.

**Comment by thijstriemstra** [comment]
> Yep, but it actually "fixed" the generated code, and it will be rewritten discarding all "fixes" upon next build/regeneration, so, to fix it properly I am editing the transpilation/generator rules in transpile.js.

Cool. The transpiled code will have to look exactly the same for `flake8` to pass. Good work!

**Comment by kroitor** [comment]
Ok, I think I merged it, and you're in the list of contributors as well, but I will have to edit __init__.py  further to filter out whitespace in transpiler now and in the base methods as well, so, work still in progress.

**Comment by kroitor** [comment]
Now Travis fails to build it, some kind of arg format issue:
https://travis-ci.org/kroitor/ccxt/builds/264113973

**Comment by kroitor** [comment]
BTW, in the end, I think PEP-8/flask8 is dumb:

```
# This is much more readable...:

class CCXTError            (Exception):    pass
class ExchangeError        (CCXTError):    pass
class AuthenticationError  (CCXTError):    pass
class NetworkError         (CCXTError):    pass
class DDoSProtection       (NetworkError): pass
class RequestTimeout       (NetworkError): pass
class ExchangeNotAvailable (NetworkError): pass

# ... than this:

class CCXTError (Exception): pass
class ExchangeError (CCXTError): pass
class AuthenticationError (CCXTError): pass
class NetworkError (CCXTError): pass
class DDoSProtection (NetworkError): pass
class RequestTimeout (NetworkError): pass
class ExchangeNotAvailable (NetworkError): pass
```

**Comment by thijstriemstra** [comment]
> # This is much more readable...

It's readable but from a 'is this correct code' point of view I would have to scan these lines twice before I could conclude it's correct. With the other version I would see it's correct right away.

**Comment by kroitor** [comment]
```
    @staticmethod
    def decimal(number):
        return str(decimal.Decimal(str(number)))
```

↑ Readable? Not sure. Correct? Well, as long as it's unreadable, don't know, have to check twice.

```
    @staticmethod
    def decimal (number):
        return str (decimal.Decimal (str (number)))
```
↑ Readable? Yep. Correct? As long as it's readable I don't have to check twice (that is exactly what readability means to me). Don't know why would Python people prefer to write it in the most crumpled way possible... The only explanation to me here - it's for historical reasons and too many people are used to a bad style. If you think of it in its core, this is what makes programming difficult to learn for newbies. The clumsy crumpled text, which is hard to separate into 'words' which are easier to read when separated by a whitespace.

But, if Python community insists, I have no option other than to obey )

**Comment by thijstriemstra** [comment]
> Don't know why would Python people prefer to write it in the most crumpled way possible... 

Less code/characters == less bugs.

**Comment by kroitor** [comment]
> Less code/characters == less bugs.

Yeah, but, less space = less readable = more bugs. )

**Comment by kroitor** [comment]
```Python
#PEP8
collections.OrderedDict(sorted(dictionary.items(), key=lambda t: t[0]))
```
```
#Me
collections.OrderedDict (sorted (dictionary.items (), key = lambda t: t[0]))
```
PEP8 improves readability! Cmon! It's a joke, right? ) I improve readability, and PEP does not )

**Comment by thijstriemstra** [comment]
Sorry ;) the 2nd version looks like it's code that has fallen apart IMO.

**Comment by kroitor** [comment]
> Sorry ;) the 2nd version looks like it's code that has fallen apart IMO.

To me the first one looks like I am listing the `collections.OrderedDict(sorted(dictionary.items()` and then, after a comma, the `key=lambda t:t[0]))`. ))

BTW, I would recommend you try this style, just for experiment. It may be hard at first, but in the end you will not want to go back to PEP, I suppose. To me whitespaced-code has much more air in it = much more freedom = much cleaner thought/programming expressions. The second one may feel like it's fallen apart, but only in the beginning. After a week, you'll hate crumpled code. And it usually does not work out-of-the box, because it's crumpled ) And another "pro" point for more air – newbies will thank you )

**Comment by kroitor** [comment]
@thijstriemstra please don't take it too serious or too personal, I'm just chatting with you in friendly mode, I still appreciate the work you've done and I am merging it to conform to PEP8 anyway )

**Comment by cleivson** [comment]
> Less code/characters == less bugs.
Less code -> less bugs? Probably.
But, less characters? It doesn't make sense at all. I believe you didn't actually mean it. Only thinking about one-char variables...
I wanted to clarify this because it's a public project  and some thoughts could be misleading to the community. Sorry for bothering...

**Comment by cleivson** [comment]
Oops, only first line should be quoted..

**Comment by kroitor** [comment]
@cleivson yeah, and you confused the discussion "a little", but it's ok )

**Comment by kroitor** [comment]
Ignore my previous comment, I confused it myself %)

**Comment by kroitor** [comment]
Done! )

**Comment by kroitor** [comment]
The tox is broken after a most recent update on Travis CI (trusty):

https://travis-ci.org/kroitor/ccxt/builds/272970898
https://travis-ci.org/kroitor/ccxt/builds/272973015
https://travis-ci.org/kroitor/ccxt/builds/272974302
https://travis-ci.org/kroitor/ccxt/builds/272975444
https://travis-ci.org/kroitor/ccxt/builds/272976928
https://travis-ci.org/kroitor/ccxt/builds/272977502

Whatever I do, it doesn't want to see tox, or complains about permissions.

@thijstriemstra , If you could help us resolve this issue, we will be very thankful!

In the meantime I have no other option than to comment tox lines in .travis.yml.

**Comment by thijstriemstra** [comment]
I'll take a look @kroitor

**Comment by kroitor** [comment]
@thijstriemstra thx for your time!

**Comment by thijstriemstra** [comment]
Looks like this is the same issue: https://github.com/travis-ci/travis-ci/issues/1705

Can you use `sudo pip install` etc instead in .travis.yml?

**Comment by kroitor** [comment]
We already tried it, here's a build with sudo pip install:
https://travis-ci.org/kroitor/ccxt/builds/272993044

**Comment by kroitor** [comment]
Yes, the sudo does not solve it entirely:
https://travis-ci.org/kroitor/ccxt/builds/273039903
Now tox is complaining as if it understands 2.7 syntax only...

**Comment by thijstriemstra** [comment]
Ok that makes sense. flake8 (and the whole travis env) needs to use Python 3. Let me check.

**Comment by kroitor** [comment]
This is where I'm stuck so far: https://travis-ci.org/kroitor/ccxt/builds/273042287

**Comment by thijstriemstra** [comment]
@kroitor can you change python3.5 to python3 in tox.ini's basepython?

**Pull request merged**
