### PR TITLE
btce/liqui and bittrex fetchOrder, btce/liqui unified createOrder return

### PR DESCRIPTION
**Pull request by Nilotaviano**
The third one is the charm, I hope 😂

### CODE REVIEW

**Comment by kroitor** [comment]
Yay! ) I will merge it for now, though we might have to rethink the contents of the fetchOrder for consistency across all markets (the fieldset I mean). But, so far, so good, we will make several implementations, and then derive a common subset of fields from them.

**Comment by Nilotaviano** [comment]
Yeah, I only put in the minimum amount of fields I thought necessary, to minimize any possible inconsistencies between different exchanges.

**Comment by Nilotaviano** [comment]
I basically have no idea how to implement this for poloniex, though. We might need a workaround for that one.

**Comment by kroitor** [comment]
Yeah, me too. For poloniex we might have to cache them locally, and use a mix of returnOpenOrders with the cache, as you said previously. Will think about it. Also, I'll contact their support to see if they have an undocumented method for that (this might also be the case, many exchanges actually have a more sophisticated API, but their docs are bad).
Btw, new version 1.3.24 is now available for downloading )

**Comment by Nilotaviano** [comment]
Thanks!

**Pull request merged**
