### PR TITLE
Fix python3

### PR DESCRIPTION
**Pull request by gnmerritt**
This PR fixes a couple python 3 compatibility issues I ran into, and adds some lightweight testing to try and help catch regressions in the future.

   - added a `tox` config for ensuring that `test.py` runs all the way through
   - added a `.travis.yml` that runs `tox` against a bunch of versions of python

If you guys go and enable travis-ci for the repository new pull requests and commits to master will run tests. See https://github.com/gnmerritt/ccxt/pull/1 for example of what that looks like

### CODE REVIEW

**Comment by kroitor** [comment]
Thank you a lot! I merged all of these commits into the main repo.

**Comment by kroitor** [comment]
The only thing I could not integrate is the following change in `__init__.py` inside the definition of fetch_products function:
```diff
- for p in range (0, len (keys)):
-     key = keys[p]
+ for key in keys:
```
Having two lines instead of one there is intentional and preferred for code consistency across JavaScript/Python/PHP (where Python and PHP versions are generated by the transpile.js script from the JavaScript version upon new releases). One line is shorter in syntax, but those two lines are more convenient for transpilation to other languages.

**Comment by gnmerritt** [comment]
Ahh interesting, that explains the unusual python form. 
 The problem there is that in python3 the keys() functions on dictionaries doesn't return a list so you can't access elements with the [] operator. I think if you update the code generation to wrap `list(dictionary.keys())` it should work

**Comment by kroitor** [comment]
Wow, thank you for that hint! I will modify the transpilation script ASAP! )

**Comment by kroitor** [comment]
Done. Appreciate your help!

**Comment by gnmerritt** [comment]
Thank you for making the library! 

If you want the tests to run automatically for every new commit to master you can go over to https://travis-ci.org/profile/kroitor and turn on travis for the repo.

**Pull request merged**
