### PR TITLE
btce/liqui and bittrex fetchOrder, btce/liqui unified createOrder return

### PR DESCRIPTION
**Pull request by Nilotaviano**

### CODE REVIEW

**Comment by kroitor** [comment]
Thanks! ) Travis is complaining, if you push while it is building (the previous build will fail), so everything should be ok after I restarted the test again. If it's not, I'll fix it )

**Comment by kroitor** [comment]
He doesn't like this line:
```JavaScript
'type': (orderInfo['Type'] == 'LIMIT_BUY') 'buy' ? 'sell',
```

Should be 
```JavaScript
'type': (orderInfo['Type'] == 'LIMIT_BUY') ? 'buy' : 'sell',
```

It's even better if you make a variable for the type, to ease the transpilation, like so:
```JavaScript
let foobar = (orderInfo['Type'] == 'LIMIT_BUY') 'buy' ? 'sell';
// ...
'type': foobar,
// ...
```

**Comment by kroitor** [comment]
Are you going to finish this? If not, let me know, I will do the merge ) Thx!

**Comment by Nilotaviano** [comment]
Yup, I've fired up my c9.io instance to be able to run tests. Thanks!

**Comment by kroitor** [comment]
Ok, if you have any questions – feel free to ask! Thanks for you involvement!

**Comment by Nilotaviano** [comment]
Sure will do! Thank you for your help!

**Comment by kroitor** [comment]
Also, note that some of the exchanges may not be accessible from your location – that is normal. The tests will show that to you, but will pass disregarding the inaccessible exchanges.

**Comment by kroitor** [comment]
And one more thing, before I forgot ))
If you see an auth error – that is because someone is using my testing keys.json with an overrided milliseconds Nonce. After that the default seconds-Nonce may not work with that particular keypair. And I have to refresh those keypairs from time to time ) So, if it complains about the nonce – blame that unknown guy )) It's also ok, the tests will still pass.

**Comment by Nilotaviano** [comment]
Got it!

**Pull request closed without merging**
