### PR TITLE
Add okex support

### PR DESCRIPTION
**Pull request by materemias**
first commit is master files

### CODE REVIEW

**Comment by materemias** [comment]
I could not test it live, please check it

**Comment by kroitor** [comment]
@materemias are you done with it or should we wait for more to come? I mean, it's not enough to copypaste that code, there should be methods added (subclassed properly) for it to work with 'future_*' endpoints by means of the unified API. Will you do that, or should we take on it?

**Comment by kroitor** [comment]
Ok, I've added it to master, but most of unified methods will not work with it yet, we will add them in a day. For now, you can use the custom OKEX public and private API from ccxt, the unified API is on the way! Thx!

**Comment by materemias** [comment]
awesome, how much does it take to be installable from repos with pip?

**Comment by kroitor** [comment]
3-4 minutes )

**Comment by kroitor** [comment]
You can watch the build process here: https://travis-ci.org/kroitor/ccxt/builds/267602767

**Comment by materemias** [comment]
great :) also 
pip install https://github.com/kroitor/ccxt/archive/master.zip
worked already

**Pull request merged**
