### PR TITLE
Unifying side and status order infos for bittrex and liqui

### PR DESCRIPTION
**Pull request by cleivson**
@kroitor , I believe these are now according to what we were thinking for polo

### CODE REVIEW

**Comment by kroitor** [comment]
Thanks! I am merging this of course! )

**Comment by kroitor** [comment]
There are some typos, like `'cancelled'` instead of `'canceled'` and `'satus'` instead of `'status'`, but I am fixing it, don't worry about it, I will upload it in a matter of several minutes.

**Comment by kroitor** [comment]
@cleivson , check it out, this is how I would do it. We definitely also need an order id, a timestamp and a symbol inside each order structure. I decoupled your implementation into corresponding parseOrder methods. Thx!

**Comment by kroitor** [comment]
Also, renamed: rate → price, startingAmount → amount

**Comment by kroitor** [comment]
Available in 1.3.118, thx again for your involvement!

**Comment by cleivson** [comment]
Sorry for the typos. I was about to put symbol inside of order, specially because it's needed for calling getOpenOrders on poloniex.

**Comment by kroitor** [comment]
Don't worry about the typos too much, I'm also making them occasionally.

**Comment by kroitor** [comment]
@cleivson check out list of our pending tasks: [Pending Tasks](https://github.com/kroitor/ccxt/blob/master/CONTRIBUTING.md#pending-tasks), this is where your help would also be appreciated a lot ) We're working on them, but if you can contribute to that as well, that would be awesome!

**Comment by cleivson** [comment]
Ok! I'm almost getting my app up and running. I may take a look on this list today )

**Pull request merged**
