### PR TITLE
use python3.5 for flake8

### PR DESCRIPTION
**Pull request by thijstriemstra**
refs #106

### CODE REVIEW

**Comment by kroitor** [comment]
Travis said:
```
qa create: /home/travis/build/kroitor/ccxt/.tox/qa
ERROR: Error creating virtualenv. Note that some special characters (e.g. ':' and unicode symbols) in paths are not supported by virtualenv. Error details: InvocationError('Failed to get version_info for python3.5: b"pyenv: python3.5: command not found\\n\\nThe `python3.5\' command exists in these Python versions:\\n  3.5\\n  3.5.3\\n\\n"',)
```

I changed it to python3 (without the `.5`), but, I suppose, it will trigger 3.4... We'll see now )

**Comment by thijstriemstra** [comment]
> I changed it to python3 (without the .5), but, I suppose, it will trigger 3.4... We'll see now )

Let's hope not, that would suck.

**Comment by kroitor** [comment]
That didn't help... It cannot select the right python for some reason...

**Comment by kroitor** [comment]
Found this: https://github.com/pyenv/pyenv-virtualenv/issues/202
But I don't know what they are talking about... where should I put it with travis... confused a little %)

**Comment by thijstriemstra** [comment]
Yea it's still using python 3.4, see https://travis-ci.org/kroitor/ccxt#L642

Let me check again.

**Pull request merged**
