### PR TITLE
fix btce private api

### PR DESCRIPTION
**Pull request by tritoanst**
add param 'method' to param api for btce

### CODE REVIEW

**Comment by xpl** [comment]
I wonder whether this will transpile to PHP/Python correctly... I thought we should enclose property names in quotes, to make them recognizeable by regexes in the `transpile.js`?

```
+                'nonce': nonce, method: path,
```

**Comment by kroitor** [comment]
> I wonder whether this will transpile to PHP/Python correctly...
Nope, it won't transpile like that, quotes should be there, I added them.

**Comment by kroitor** [comment]
@tritoanst thanks!

**Comment by xpl** [comment]
We should describe these rules in a human-readable format somewhere. Maybe add something like a **Contribution** section to the `README.md`.

**Comment by kroitor** [comment]
Should be a file named CONTRIBUTING [according to GitHub](https://opensource.guide/starting-a-project/#writing-your-contributing-guidelines)...

**Pull request merged**
