### PR TITLE
http://api.huobi.com/staticmarket/btc_kline_005_json.js?length=500

### PR DESCRIPTION
**Pull request by 86chenjie**
handle this case for huobi, make the length param valid

### CODE REVIEW

**Comment by 86chenjie** [comment]
@kroitor  this issue also need to be fixed on other language files.

**Comment by kroitor** [comment]
Thanks! This violates some rules from the [CONTRIBUTING](https://github.com/kroitor/ccxt/blob/master/CONTRIBUTING.md) document, but we will work this out and incorporate this pull request very soon (an hour or two may be necessary for testing).

**Comment by 86chenjie** [comment]
Good. Next time, i'll just create a issue.  :)

**Comment by kroitor** [comment]
This will be incorporated in version 1.1.78 in 30-40 minutes. Thanks! Also, this is how this should be done properly:
```JavaScript
        } else {
            url += '/' + type + '/' + this.implodeParams (path, params) + '_json.js';
            let query = this.omit (params, this.extractParams (path));
            if (Object.keys (query).length)
                url += '?' + this.urlencode (query);
        }
```
Thanks again for your involvement! Your help is really appreciated!

**Comment by kroitor** [comment]
This is now available with version 1.1.78. Thanks!

**Pull request merged**
